<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>true</WarningsAsErrors>
    </PropertyGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Caching.Abstractions">
        <HintPath>..\..\..\..\..\.nuget\packages\microsoft.extensions.caching.abstractions\10.0.10\lib\net10.0\Microsoft.Extensions.Caching.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>
    
</Project>
